// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBObVLos7HWfv3hXr5kGKbgMFljMxcXBkE',
    appId: '1:613109271098:web:c7649161ffdd864b7b4303',
    messagingSenderId: '613109271098',
    projectId: 'controle-saida-aluno',
    authDomain: 'controle-saida-aluno.firebaseapp.com',
    storageBucket: 'controle-saida-aluno.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG2LqC6warQ1EwKaYfbi_O6hY7ET5uVaI',
    appId: '1:613109271098:android:39aed3fe1869ed237b4303',
    messagingSenderId: '613109271098',
    projectId: 'controle-saida-aluno',
    storageBucket: 'controle-saida-aluno.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDscpdGv2UD8PhIAYGzwVm1cs5Y9qOKEFQ',
    appId: '1:613109271098:ios:c61e449d951d4bf57b4303',
    messagingSenderId: '613109271098',
    projectId: 'controle-saida-aluno',
    storageBucket: 'controle-saida-aluno.appspot.com',
    iosBundleId: 'com.example.controleSaidaAluno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDscpdGv2UD8PhIAYGzwVm1cs5Y9qOKEFQ',
    appId: '1:613109271098:ios:db8ab749b8bb99807b4303',
    messagingSenderId: '613109271098',
    projectId: 'controle-saida-aluno',
    storageBucket: 'controle-saida-aluno.appspot.com',
    iosBundleId: 'com.example.controleSaidaAluno.RunnerTests',
  );
}
